### PR TITLE
DOC: update conda-forge installation instruction

### PR DESCRIPTION
**Pull request by dragonyanglong**

### CODE REVIEW

**Comment by dragonyanglong** [comment]
Hi @rozyczko , I created a PR for testing. Are these tests related with what you are trying to set up? It seems like failed at `artifacts github releases`

**Comment by rozyczko** [comment]
This failure in uploading to Pypi is because this repo workflow permissions don't allow branches on your repo (@dragonyanglong ) to do the upload.
You either need to modify the permissions in the diffpy.pdffit2 repo or create a local branch

**Comment by dragonyanglong** [comment]
Is it at the `Actions` tab? It seems like all permissions are allowed there.

image

**Comment by rozyczko** [comment]
I believe this option would allow it but haven't tested (In Actions/General)

fork

**Comment by rozyczko** [comment]
I believe this would help, but I haven't tested. This is in Actions/General

fork

**Comment by dragonyanglong** [comment]
@rozyczko , I tried changing the setting, but it doesn't make difference. Are we missing any info in the https://github.com/diffpy/diffpy.pdffit2/blob/master/.github/workflows/build.yaml ?

**Comment by rozyczko** [comment]
Hmm I don't think we are missing anything, considering the local (non-forked) build runs fine
https://github.com/diffpy/diffpy.pdffit2/actions/runs/4280435199

The issue is with your fork not having proper permissions, I believe.
Can you create a local branch in this project and see if it is working as expected?

**Comment by dragonyanglong** [comment]
I tried a testing PR at #13, it seems like fail for py3.10?

**Pull request merged**
