### PR TITLE
Update conda-forge version to Py 3.8-3.10

### LINKED ISSUE #18: Error when installing pdffit2 via conda-forge then running a fit on pdfgui
```
/home/sam/miniconda3/envs/pdffit2_310/lib/python3.10/site-packages/diffpy/pdfgui/gui/extendedplotframe.py:182: UserWarning: marker is redundantly defined by the 'marker' keyword argument and the fmt string "." (-> marker='.'). The keyword argument will take precedence.
  curveRef = self.subplot.plot(xData, yData, stylestr, **properties)[0]
Exception in thread Thread-2:
SystemError: PY_SSIZE_T_CLEAN macro must be defined for '#' formats

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/sam/miniconda3/envs/pdffit2_310/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/home/sam/miniconda3/envs/pdffit2_310/lib/python3.10/site-packages/diffpy/pdfgui/control/fitting.py", line 97, in run
    self.fitting.run()
  File "/home/sam/miniconda3/envs/pdffit2_310/lib/python3.10/site-packages/diffpy/pdfgui/control/fitting.py", line 402, in run
    if self.refine_step():
  File "/home/sam/miniconda3/envs/pdffit2_310/lib/python3.10/site-packages/diffpy/pdfgui/control/fitting.py", line 686, in refine_step
    finished =  self.server.refine_step(self.tolerancy)
  File "/home/sam/miniconda3/envs/pdffit2_310/lib/python3.10/site-packages/diffpy/pdffit2/pdffit.py", line 353, in refine_step
    self.finished = pdffit2.refine_step(self._handle, toler)
SystemError: <built-in function refine_step> returned a result with an exception set
Exception in thread Thread-3:
SystemError: PY_SSIZE_T_CLEAN macro must be defined for '#' formats

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/sam/miniconda3/envs/pdffit2_310/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/home/sam/miniconda3/envs/pdffit2_310/lib/python3.10/site-packages/diffpy/pdfgui/control/fitting.py", line 97, in run
    self.fitting.run()
  File "/home/sam/miniconda3/envs/pdffit2_310/lib/python3.10/site-packages/diffpy/pdfgui/control/fitting.py", line 402, in run
    if self.refine_step():
  File "/home/sam/miniconda3/envs/pdffit2_310/lib/python3.10/site-packages/diffpy/pdfgui/control/fitting.py", line 686, in refine_step
    finished =  self.server.refine_step(self.tolerancy)
  File "/home/sam/miniconda3/envs/pdffit2_310/lib/python3.10/site-packages/diffpy/pdffit2/pdffit.py", line 353, in refine_step
    self.finished = pdffit2.refine_step(self._handle, toler)
SystemError: <built-in function refine_step> returned a result with an exception set
```

### PR DESCRIPTION
**Pull request by 8bitsam**
Update the conda-forge build config to support Python 3.8-3.10. This should ensure dependencies are updating when installing via conda-forge.
Closes #18 

Ready for review and merge

### CODE REVIEW

**Review by sbillinge — COMMENTED** [review]
I think we can drop 3.5 and 3.6 here too.  In principle we are only supporting 3.9 - 3.11 atm.  However, we still have code pinned at 3.7 (diffpy-cmi) so I would rather keep things down to 3.7, or else do 3.7 and 3.9 - 3.11.

There are two ways to get to Py3.11.   
  - One is that, now we have it working locally in 3.10, we do it all again in 3.11, then we roll it out to conda-forge and make sure we can build it there.
  - Two is we take it all the way to conda-forge at 3.10 and test that we know how to make that work, then we do the work to take it to 3.11 after that.

I don't have a good answer to that, but I think that it may be quick to get it going on 3.11 (maybe it just runs locally now you know how to build it), so it might be worth trying that.  If it just goes, then let's go for broke and bring it up to date with 3.11.  If there are things to fix to make it run in 3.11, then go back to "Two"?  What do you think?

**Comment by dragonyanglong** [comment]
I agree with choice One. py3.9 to 3.10 needs some work, but py3.10 and py3.11 are similar.

**Comment by sbillinge** [comment]
This is failing CI.  A quick look suggests that the path to the release artifact may be incorrectly specified.

Also, it seems to be wanting to make a 1.4.0 release but don't we want to bump it to 1.4.1?  

@dragonyanglong @8bitsam @robothamevan

**Comment by 8bitsam** [comment]
I bumped to 1.4.1, but still need to check to make sure the test passes. I changed the build.yaml file based on github's recommendations for fixing the error that appeared in the test.

**Comment by dragonyanglong** [comment]
@sbillinge @8bitsam did this PR support newer version of python?

**Pull request merged**
