### PR TITLE
try building wheels with CI for pdffit2

### PR DESCRIPTION
**Pull request by Tieqiong**
This is only for exhibition purposes for a cpython package. Final changes should be done on release-script

### CODE REVIEW

**Comment by Tieqiong** [comment]
need to change something with linux

**Comment by Tieqiong** [comment]
windows still producing wheels that lack proper dll. It seems like the problem is not about installing with conda or vcpkg

**Comment by sbillinge** [comment]
thanks for the hard work on this @Tieqiong

**Comment by Tieqiong** [comment]
@sbillinge 

Very weird. It was giving that dll error on Friday but when I randomly trying it again it's working. It would be nice if we can test the windows wheel on your machine. You can grab it by going into the wheel builder action job (windows-latest with the right python version) and there will be a GitHub link under `Run actions/upload-artifact@v4`. Download the file and run `pip install diffpy.pdffit2-0.0.1-cp312-cp312-win_amd64.whl` (taking the py3.12 one as example), then `conda install pytest` and pytest. Thanks

**Comment by Tieqiong** [comment]
Tested with a VM and it's still showing the error. Will figure it out

**Comment by Tieqiong** [comment]
This is ready, just need someone test the wheel for Intel Mac (intel M1, using the macOS-13 wheel).

**Comment by sbillinge** [comment]
great news @Tieqiong !

**Comment by Tieqiong** [comment]
closing as completed

**Pull request closed without merging**
