### PR TITLE
Add separate install instructions for macOS Arm64 users in readme

### PR DESCRIPTION
**Pull request by bobleesj**
Closes https://github.com/diffpy/diffpy.pdffit2/issues/86
Closes https://github.com/diffpy/diffpy.pdffit2/issues/24 

Here is the rendered version of the REAMDE: 

https://github.com/bobleesj/diffpy.pdffit2/tree/readme-install?tab=readme-ov-file#installation

### CODE REVIEW

**Comment by bobleesj** [comment]
@sbillinge ready for review - Codecov error is occuring for some reason. I will address it in the next PR.

**Comment by bobleesj** [comment]
I will try to re-run the CI with an empty commit.

**Comment by bobleesj** [comment]
@sbillinge okay.. it was a glitch. Codecov works now.

**Comment by sbillinge** [comment]
let's remove this from the installation in the readme (and the docs if it is there), it is just confusing:

diffpy.pdffit2 supports Python 3.11 and 3.12 the following external software:

    setuptools - software distribution tools for Python
    python-dev - header files for interfacing Python with C
    GSL - GNU Scientific Library for C
    g++ - GNU C++ compiler
    diffpy.structure - simple storage and manipulation of atomic structures, https://github.com/diffpy/diffpy.structure

Also, something happened to the rendering of the "conda config --add channels conda-forge".

Other than that it looks great!

**Comment by bobleesj** [comment]
@sbillinge Got it. the `conda config --add channels conda-forge"` is fixed and also removed dependencies for building. 

Screenshot 2024-12-04 at 10 04 51 PM

**Comment by sbillinge** [comment]
Nicely done. Let me know when we are ready for PDFgui/PDF fit 2 release.

**Pull request merged**
